config/routes.rb
Mybooks::Application.routes.draw do
  root to: 'pages#front'
  get '/home', to: 'books#index'
  get '/register', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  get '/reading_queue', to: 'queue_items#index'
  get '/archives', to: 'archives#index'

  resources :books, only: [:show] do
    collection do
      get '/search', to: 'books#search'
    end
    resources :reviews, only: [:create]
  end

  resources :users, only: [:create]
  resources :sessions, only: [:create]
  resources :notes, except: [:destroy]
  resources :categories, only: [:show]
  resources :archives, only: [:create]
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'
end

app/models/archive.rb
class Archive < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category

  has_many :reviews, -> { order("created_at DESC") }
  has_many :archives

  validates_presence_of :title

  def self.search_by_title(keyword)
    return [] if keyword.blank?
    where("title ILIKE ?", "%#{keyword.downcase}%").order("created_at DESC")
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books, -> { order("created_at DESC") }

  validates_presence_of :name

  def recent_books
    books.first(4)
  end
end

app/models/queue_item.rb
class QueueItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  delegate :category, to: :book
  delegate :title, to: :book, prefix: :book

  validates :position, numericality: { only_integer: true }

  def rating
    review.rating if review
  end

  def rating=(new_rating)
    if review
      review.update_column(:rating, new_rating)
    else
      review = Review.new(user: user, book: book, rating: new_rating)
      review.save!(validate: false)
    end
  end

  def category_name
    category.name
  end

  private

  def review
    @review ||= Review.find_by(user_id: user.id, book_id: book.id)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates_presence_of :rating, :content
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates_presence_of :password

  has_many :reviews
  has_many :queue_items, -> { order(:position) }
  has_many :archives, -> { order("created_at DESC")}

  has_secure_password validations: false

  def queued_book?(book)
    queue_items.map(&:book).include?(book)
  end

  def queue_item_in_queue?(queue_item)
    queue_items.include?(queue_item)
  end

  def normalize_queue_item_positions
    queue_items.each_with_index do |queue_item, idx|
      queue_item.update!(position: idx + 1)
    end
  end

  def previously_read_books
    archives
  end

  def archived_book?(book)
    archives.map(&:book).include?(book)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_user
    redirect_to sign_in_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :require_user

  def index
    @archives = current_user.previously_read_books
  end

  def create
    @book = Book.find(params[:book_id])
    Archive.create(book: @book, user: current_user) unless current_user.archived_book?(@book)
    redirect_to archives_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user

  def index
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end

  def search
    @results = Book.search_by_title(params[:keyword])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
    redirect_to home_path if current_user
  end
end

app/controllers/queue_items_controller.rb
class QueueItemsController < ApplicationController
  before_action :require_user

  def index
    @queue_items = current_user.queue_items
  end

  def create
    book = Book.find(params[:book_id])
    queue_book(book)
    redirect_to reading_queue_path
  end

  def update_queue
    begin
      update_queue_items
      current_user.normalize_queue_item_positions
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = "Invalid position number."
    end
    redirect_to reading_queue_path
  end

  def destroy
    queue_item = QueueItem.find(params[:id])
    queue_item.destroy if current_user.queue_item_in_queue?(queue_item)
    current_user.normalize_queue_item_positions
    redirect_to reading_queue_path
  end

  private

  def queue_book(book)
    QueueItem.create(book: book, user: current_user, position: new_queue_item_position) unless current_user.queued_book?(book)
  end

  def new_queue_item_position
    current_user.queue_items.count + 1
  end

  def update_queue_items
    ActiveRecord::Base.transaction do
      params[:queue_items].each do |queue_item_data|
        queue_item = QueueItem.find(queue_item_data["id"])
        queue_item.update!(position: queue_item_data["position"], rating: queue_item_data["rating"]) if queue_item.user == current_user
      end
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user

  def create
    @book = Book.find(params[:book_id])
    review = @book.reviews.build(review_params.merge!(user: current_user))

    if review.save
      flash[:success] = "Your review has been added."
      redirect_to @book
    else
      flash[:danger] = "Review field cannot be blank."
      @reviews = @book.reviews.reload
      render 'books/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have logged in successfully!"
      redirect_to home_path
    else
      flash[:danger] = "Invalid email and password."
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have signed out successfully!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to sign_in_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def options_for_rating(selected = nil)
    options_for_select((1..5).map { |number| [pluralize(number, "Star"), number] }, selected)
  end
end

app/views/archives/index.html.haml
.books.container-fluid
  %section.col-md-10.col-md-offset-1
    .row
      - @archives.each do |archive|
        .book.col-sm-3
          = link_to archive.book, class: "text-info" do
            = image_tag archive.book.small_cover_url
            %h5= archive.book.title

app/views/books/index.html.haml
.books.container-fluid
  - @categories.each do |category|
    %section.col-sm-10.col-sm-offset-1
      %h3
        = link_to category.name, category, class: "text-info"
      .books_category.row
        - category.books.each do |book|
          .book.col-sm-3
            = link_to book, class: "text-info" do
              = image_tag book.small_cover_url
              %h5= book.title

app/views/books/search.html.haml
.books.container-fluid
  %section.col-md-10.col-md-offset-1
    .row
      - @results.each do |book|
        .book.col-sm-3
          = link_to book, class: "text-info" do
            = image_tag book.small_cover_url
            %h5= book.title

app/views/books/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-5.col-sm-offset-1
        %img(src="/tmp/book-large-cover.jpg")
      .book_info.col-sm-4
        %header
          %h3= @book.title
          %span Rating: 4.0/5.0
        %h4 Description
        %p= @book.description
        .actions
          - if current_user.queued_book?(@book)
            %button.btn.btn-success(disabled="disable")
              Currently in queue
          - else
            = link_to "+ Add to Queue", queue_items_path(book_id: @book.id), method: :post, class: "btn btn-success"
          - if current_user.archived_book?(@book)
            %button.btn.btn-danger(disabled="disabled")
              Marked as read
          - else
            = link_to "Mark as read", archives_path(book_id: @book.id), method: :post, class: "btn btn-danger"


%section.reviews
  .container
    .row
      .col-sm-10.col-sm-offset-1
        = bootstrap_form_for [@book, Review.new] do |f|
          %fieldset
            .form-group
              = f.label "Rate this book"
              .row
                .col-sm-3
                  = f.select :rating, options_for_rating, {}, { class: "form-control" }
            .form-group
              .row
                .col-sm-10
                  = f.text_area :content, rows: 6, class: "form-control", label: "Write Review"
          %fieldset.form-group.clearfix
            = f.submit :Submit, class: "btn"
            = link_to :Cancel, @book
        %header
          %h4 User Reviews (#{@reviews.count})
        .book-reviews.list-group
          - @reviews.each do |review|
            %article.review.row
              .col-sm-2
                %span Rating: #{review.rating} / 5
                %p
                  by:
                  = link_to review.user.username
              .col-sm-8
                %p #{review.content}

app/views/categories/show.html.haml
.books.container-fluid
  %section.col-md-10.col-md-offset-1
    %h3= @category.name
    .books_category.row
      - @category.books.each do |book|
        .book.col-sm-3
          = link_to book, nil do
            = image_tag book.small_cover_url
            %h5= book.title

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title MyBooks - a book manager app
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header.main
      = render 'shared/header'
    .container
      = render 'shared/messages'
      = yield
    %footer
      .container.col-md-10.col-md-offset-1
        %center
          &copy 2015 MyBooks

app/views/pages/front.html.haml
.jumbotron
  %h1
    Book Manager
    %p for the old-fashioned, but tech-savvy.
    %p= link_to 'Sign up now', register_path, class: 'btn btn-primary btn-lg'
  %section
    %small
      Already have an account?
      = link_to 'Sign in', sign_in_path

app/views/queue_items/index.html.haml
%section.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %h2 Reading Queue
        = form_tag update_queue_path do
          %table.table.table-striped
            %thead
              %tr
                %th(width="20%") List Order
                %th(width="30%") Book Title
                %th(width="20%") Rating
                %th(width="20%") Category
                %th(width="10%") Remove
            %tbody
              - @queue_items.each do |queue_item|
                %tr
                  = hidden_field_tag "queue_items[][id]", queue_item.id
                  %td
                    = text_field_tag "queue_items[][position]", queue_item.position, class: "form-control"
                  %td
                    = link_to queue_item.book_title, queue_item.book
                  %td
                    = select_tag "queue_items[][rating]", options_for_rating(queue_item.rating), { include_blank: true, class: "form-control" }
                  %td
                    = link_to queue_item.category_name, queue_item.category
                  %td
                    = link_to queue_item, method: :delete do
                      %i.glyphicon.glyphicon-remove
          = submit_tag 'Update Queue', class: 'btn btn-danger'

app/views/shared/_header.html.haml
#top-header.container.col-sm-10.col-sm-offset-1
  .row
    %nav.navbar.navbar-inverse(role="navigation")
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed(type="button" data-toggle="collapse" aria-expanded="false")
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to 'MyBooks', root_path, class: 'navbar-brand'

        .collapse.navbar-collapse
          - if current_user
            %ul.nav.navbar-nav
              %li
                =link_to 'Library', home_path
                %span.sr-only
              %li
                = link_to 'Reading Queue', reading_queue_path
              %li
                = link_to 'Archives', archives_path
            = form_tag search_books_path, method: :get, class: "navbar-form navbar-left" do
              .form-group
                = text_field_tag :keyword, nil, placeholder: "Search", class: "form-control"
              .form-group
                = submit_tag :Submit, class: "btn btn-default"
          %ul.nav.navbar-nav.navbar-right
            - if !current_user
              %li
                =link_to 'Register', register_path
              %li
                =link_to 'Sign in', sign_in_path
            - if current_user
              %li.dropdown
                %a.dropdown-toggle(href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false")
                  = "#{current_user.username}"
                  %span.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Sign out', sign_out_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/users/new.html.haml
.register.container-fluid
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @user, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-4' do |f|
        %header
          %h2 Register
        %fieldset
          = f.email_field :email, label: 'Email Address'
          = f.password_field :password, label: 'Password'
          = f.text_field :username, label: 'Username'
          = f.form_group do
            = f.submit 'Sign up', class: 'btn btn-primary'